Sivigik/urls.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, include, url
from django.contrib import admin

from Sivigik.settings import IS_MAINTENANCE, MEDIA_ROOT, STATIC_ROOT

from sitemap import *

admin.autodiscover()
sitemaps = {
    'main': BaseSitemap,
    'articles':ArticleSitemap,
    'categories':CategorySitemap,
}

if IS_MAINTENANCE:
    urlpatterns = patterns('',
        url(r'^admin/', include(admin.site.urls)),
        url(r'', include('maintenance.urls', namespace='maintenance')),
)
else: 
    urlpatterns = patterns('',
        # Examples:
        # url(r'^$', 'Sivigik.views.home', name='home'),
        # url(r'^blog/', include('blog.urls')),
	    url(r'^article/', include('article.urls', namespace="article")),
        url(r'^search/', include('search.urls', namespace="search")),
        url(r'^admin/', include(admin.site.urls)),
	    url(r'^$', include('home.urls', namespace="home")),
	    url(r'^categories/', include('home.urls', namespace="home")),
        url(r'^member/', include('member.urls', namespace="member")),
        url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT}),
        url(r'^staticcontent/', include('staticContent.urls', namespace="staticContent")),
    )

home/urls.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
	url(r'^$', views.home, name='index'),
    url(r'^(?P<category_name>[A-Za-z]+)/$', views.category, name='category'),
)

member/urls.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, url

from member import views

urlpatterns = patterns('',
    url(r'^login/$', views.connect, name='login'),
    url(r'^logout/$', views.disconnect, name='logout'),
    url(r'^profil/$', views.profil, name='profil'),
    url(r'^articles/$', views.article_list, name='articles_list'),
    url(r'^set_password/$', views.set_password, name='set_password'),
    url(r'^create_author/$', views.create_author, name='create_author'),
    url(r'^change_avatar/$', views.change_avatar, name='change_avatar'),
    url(r'^static_pages/$', views.static_pages_list, name='static_pages_list'),
)

article/models.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar. If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from home.models import Event
from member.models import Member

class Article(models.Model):
    event = models.ForeignKey(Event)
    author = models.ForeignKey(Member)
    is_beta = models.BooleanField()
    introduction = models.TextField()
    def __unicode__(self):
        return self.event.name
    def get_absolute_url(self):
        return '/article/' + str(self.pk) + '/'

    def get_edit_url(self):
        return '/article/' + str(self.pk) + '/edit/'

    def get_comment_url(self):
        return '/article/' + str(self.pk) + '/comments/'

    def get_as_dict(self):
        returned = {}
        returned['event'] = self.event.pk
        returned['author'] = self.author.pk
        returned['is_beta'] = self.is_beta
        returned['pk'] = self.pk
        #returned['parts'] = []
        #for p in self.parts:
        #    returned['parts'].append(p.pk)
        return returned
    def load_from_dict(self, d):
        if 'event' in d:
            self.event = Event.objects.get(pk=d['event'])
        if 'author' in d:
            self.author = Author.objects.get(pk=d['author'])
        if 'is_beta' in d:
            self.is_beta = d['is_beta']
        if 'pk' in d:
            self.pk = d['pk']


class Part(models.Model):
    text = models.TextField()
    title = models.CharField(max_length=200)
    article = models.ForeignKey(Article, related_name='parts')
    def __unicode__(self):
        return self.title
    def get_as_dict(self):
        returned = {}
        returned['text'] = self.text
        returned['title'] = self.title
        returned['article'] = self.article.pk
        return returned
    def load_from_dict(self, d):
        if 'text' in d:
            self.text = d['text']
        if 'title' in d:
            self.title = d['title']
        if 'article' in d:
            self.article = Article.objects.get(pk=d['article'])

class Comment(models.Model):
    text = models.TextField()
    article = models.ForeignKey(Article, related_name='comments')
    member = models.ForeignKey(Member, related_name='comments')
    def __unicode__(self):
        return self.text

member/models.py
from django.db import models
from django.core.files import File
from django.contrib.auth.models import User
from django.db.models.query import QuerySet

from django.utils import timezone

class Member(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(null=True, blank=True, upload_to="avatar/")
    is_author = models.BooleanField()

    def __unicode__(self):
        return u"Profil de {0}".format(self.user.username)

staticContent/models.py
from django.db import models
from member.models import Member

class StaticContent(models.Model):
    content = models.TextField()
    style = models.TextField()
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Member)
    def __unicode__(self):
        return self.title

member/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.formsets import formset_factory

from member.models import Member

class CreateMemberForm(forms.Form):
    
    error_css_class = 'error'
    pseudo = forms.CharField(max_length=200, label=u'Pseudo :')
    addr = forms.EmailField(label=u'Adresse mail (ne sera pas divulguée) :')
    password = forms.CharField(max_length=50, label=u"Mot de passe", widget=forms.PasswordInput)
    cond = forms.BooleanField(label=u"J'ai lu et j'accepte les conditions d'utilisation de sivigik")

member/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate
from django.contrib.auth.views import login, logout, password_change
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required

from django.views import generic

from member.forms import CreateMemberForm#, ChangeAvatarForm
from member.models import Member
from article.models import Article

def connect(request):
    return login(request, template_name="member/login.html")

@login_required(login_url='/member/login/')
def disconnect(request):
    return logout(request, next_page='/', template_name='member/logout.html')

@login_required(login_url='/member/login/')
def set_password(request):
    return password_change(request, template_name='member/set_password.html', post_change_redirect='/member/profil')

@login_required(login_url='/member/login/')
def  profil(request):
    return render(request, 'member/profil.html')

@login_required(login_url='/member/login/')
def article_list(request): 
    the_member = request.user.member
    return render(request, 'member/article_list.html', {'member':the_member})

@login_required(login_url='/member/login/')
def change_avatar(request):
    if request.method == 'POST':
        form = ChangeAvatarForm(request.POST, request.FILES)

        if form.is_valid():

            avatar = form.cleaned_data['avatar']

            request.user.member.avatar = avatar
            request.user.member.save()

            changed = True
    else:
        form = ChangeAvatarForm()

    return render(request, 'member/change_avatar.html', locals())

@login_required(login_url='/member/login/')
def static_pages_list(request):
    the_member = request.user.member
    return render(request, 'member/static_pages_list.html', {'member':the_member})

@permission_required('is_superuser')
def create_author(request):
    if request.method == 'POST':
        form = CreateAuthorForm(request.POST, request.FILES)

        if form.is_valid():

            the_member = form.cleaned_data['member']

            the_member.is_author = True
            the_member.save()

            created = True
    else:
        form = CreateAuthorForm()

    return render(request, 'member/create_author.html', locals())
    

member/templates/member/article_list.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block style %}<link rel="stylesheet" type="text/scss" href="{% static 'member/style.scss' %}" />{% endblock %}

{% block title %}{{member.user.username}}{% endblock%}

{% block article_title %}<div id="page_title">Articles de {{member.user.username}}</div>{% endblock %}
{% block content%}
{%if member.is_author %}
<ul>
    {% for article in member.article_set.all %}
    <li><a href='/article/{{article.id}}'>{{article.event.name}}</a></li>
    {% endfor %} 
    <li><a href='/article/new/' class='new_article'>Créer un nouvel article.</a></li>
</ul>
{%else%}
<h2>Vous n'&ecirc;tes pas auteur.</h2>
{%endif%}
{%endblock %}

member/templates/member/change_avatar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}<link rel="stylesheet" type="text/scss" href="{% static 'member/style.scss' %}" />{% endblock %}

{% block title %}{{user.username}}{% endblock %}
{% block article_title %}<div id="page_title">Changement d'avatar</div>{% endblock %}

{% block content %}
{% if changed %}<h3>Avatar changé.</h3>{% endif %}

<form action="/member/change_avatar/" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

member/templates/member/create_author.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}<link rel="stylesheet" type="text/scss" href="{% static 'member/style.scss' %}" />{% endblock %}

{% block title %}{{user.username}}{% endblock %}
{% block article_title %}<div id="page_title">Création d'auteur</div>{% endblock %}

{% block content %}
{% if created %}<h3>Auteur créé.</h3>{% endif %}

<form action="/member/create_author/" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

member/templates/member/login.html
{% extends 'base.html' %}

{%load staticfiles %}
{%block style%}<link rel="stylesheet" type="text/scss" href="{% static 'member/style.scss' %}" />{%endblock%}

{% block title%}login{% endblock %}

{% block content %}

{% if form.errors %}
<p>Vos identifiants sont incorrects.</p>
{% endif %}

<form method="post" action="/member/login/">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="/" />
</form>
{% endblock %}

member/templates/member/logout.html
{%extends 'base.html' %}

{% block title%}logout{%endblock%}

{%block article_title%}
Vous avez été déconnecté
{%endblock%}

member/templates/member/profil.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}<link rel="stylesheet" type="text/scss" href="{% static 'member/style.scss' %}" />{% endblock %}

{% block title %}{{user.username}}{% endblock %}
{% block article_title %}<div id="page_title">Profil</div>{% endblock %}

{% block content %}
<ul>
    <li><a class='button right_arrow full_width' href='/member/set_password/'>Changer mon mot de passe</a></li>
    <li><a class='button right_arrow full_width' href='/member/change_avatar/'>Changer mon avatar</a></li>
    {%if user.member.is_author%}
    <li><a class='button right_arrow full_width' href='/member/articles/'>Mes articles</a></li>
    <li><a class='button right_arrow full_width' href='/member/static_pages/'>Mes pages statiques</a></li>
    {%endif%}
    <li><a class='button right_arrow full_width' href='/member/logout/'>logout</a></li>
    {% if user.is_superuser %}
    <li><a class='button right_arrow full_width' href='/member/create_author/'>Créer un auteur</a></li>
    {% endif %}
</ul>
{% endblock %}

member/templates/member/set_password.html
{% extends 'base.html' %}
{% load i18n %}
{%load staticfiles %}
{%block style%}<link rel="stylesheet" href="{% static 'member/style.scss' %}" />{%endblock%}

{% block title%}Mot de passe{% endblock %}

{% block content %}
{% if form.errors %}
<p>Il y a une erreur...</p>
{%endif%}
<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
<table>
<tr>
    <td>Ancien mot de passe</td>
    <td>{{ form.old_password }}</td>
</tr>
<tr>
    <td>Nouveau mot de passe</td>
    <td>{{ form.new_password1 }}</td>
</tr>
<tr>
    <td>Nouveau mot de passe (encore)</td>
    <td>{{ form.new_password2 }}</td>
</tr>
</table>
<p><input type="submit" value="{% trans 'Change' %}" /></p>
</form>

{% endblock %}

member/templates/member/static_pages_list.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block style %}<link rel="stylesheet" href="{% static 'member/style.scss' %}" />{% endblock %}

{% block title %}{{member.user.username}}{% endblock%}

{% block article_title %}<div id="page_title">Pages de {{member.user.username}}</div>{% endblock %}
{% block content%}
{% if member.is_author %}
<table>
    {% for page in member.staticcontent_set.all %}
    <tr><td>{{page.title}} <td><a class='button right_arrow full_width' href='/staticcontent/{{page.pk}}?f=/member/static_pages/'>Voir la page</a>
                    <a class='button right_arrow full_width validate' href='/staticcontent/{{page.pk}}/edit/'>Éditer la page</a></td></tr>
    {% endfor %} 
    <tr><td colspan="2"><a href='/staticcontent/new/' class='button right_arrow full_width'>Créer une nouvelle page statique.</a></td></tr>
</table>
{%else%}
<h2>Vous n'&ecirc;tes pas auteur.</h2>
{%endif%}
{%endblock %}